---
title: "Week 9 - What makes a good index?"
format: html
---

For this assignment, we will be using this file: `big-fat.sqlite3` and this query: 

```{sql}
SELECT Nest_ID
    FROM Bird_nests
    WHERE Site = 'nome' AND
          Species = 'ruff' AND
          Year = 1983 AND
          Observer = 'cbishop' AND
          ageMethod = 'float';
```

## Part 1:

Is there already an index on the Bird_nests table? If so, what is that index and will SQLite use it in the above query? Why or why not?

We know that the primary key for the Bird_nests table is Nest_ID, which has a unique identifier for each row in the table. Therefore, it would make sense that this would be the index for the table. Because Nest_ID is included in the SELECT clause, I do think it would be used in the query above. If it was not included in any of the SELECT or WHERE statements, I don't think it would be included. But it is here. 

Will adding an index on a column not mentioned in the WHERE clause be used by the database? Why or why not?

The database would not use any indexes that are not mentioned in the WHERE clause because it has no need for it. The use of the index is to allow for faster searching and filtering, so if a column isn't mentioned in the WHERE statement, the index wouldn't be used. 

## Part 2:

Experiment 1: no added index

```{sql}
-- Drop previous index if needed
DROP INDEX IF EXISTS idx_site;

-- Create index
CREATE INDEX idx_site ON Bird_nests(Site);

-- Count distinct values in the indexed column
SELECT COUNT(DISTINCT Site) AS num_distinct_site FROM Bird_nests;


bash hw5-test-harness.sh subquery 10 "SELECT Nest_ID FROM Bird_nests WHERE Site = 'nome' AND Species = 'ruff' AND Year = 1983 AND Observer = 'cbishop' AND ageMethod = 'float';" big-fat.sqlite3 index_results.csv

-- Drop the index
duckdb big-fat.duckdb "DROP INDEX idx_site;";
```

Experiment 2: Added index for Site

```{sql}

```

Experiment 3: Added index for Species

```{sql}

```

Experiment 4: Added index for Year

```{sql}

```

Experiment 5: Added index for Observer

```{sql}

```

Experiment 6: Added index for ageMethod

```{sql}

```

Experiment 7: Added index for Site, Species

```{sql}

```

Experiment 8: Added index for Site, Observer

```{sql}

```

Experiment 9: Added index for Species, Observer

```{sql}

```

Experiment 10: Added index for Year, Observer

```{sql}

```

Experiment 11: Added index for Observer, ageMethod

```{sql}

```

Experiment 12: Added index for Site, Species, Observer

```{sql}

```

Experiment 13: Added index for Site, Year, Observer

```{sql}

```

Experiment 14: Added index for Species, ageMethod, Year, Observer

```{sql}

```

Experiment 15: Added index for Species, ageMethod, Year

```{sql}

```

### Final Questions:

What relationship do you observe? Hypothesize why you see the relationship you do

What conclusion do you draw regarding what makes a good index?